feat: added modal for settings
RocketChat/AgileBot pull request #1
Opened 2024-06-14 09:56 UTC by hardikbhatia777

## Features:
1. /summarize - Summarize the updates posted by engineers in the thread (in a format).
2. /scrum - Manually post the message for engineers to provide updates.
3. /agile-settings - Opens up the main modal to control all the different aspects of scheduling the above process.

2024-06-14 09:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/AgileBot?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/AgileBot?pullRequest=1) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/AgileBot?pullRequest=1) it.</sub>

2024-06-18 03:09 UTC, scuciatto requested changes
I left a small comment in one file. We are not running  a linter here so, it is important that you use it locally. For example: normally, we use strings with single quotes. 

Other points: let's prefer i18n keys than hardcoded strings. Also, always take a look on error handling (both items could be added later if we have time left).

Another point (maybe for later if we have time), it would be nice to have tests here if possible. Remember: this is open source and, in the future, we can have contributors.

2024-06-19 09:48 UTC, hardikbhatia777 commented on AgileBotApp.ts
> +        return await handler.run(context);
@scuciatto I used the GitHub and Miro app as well as the official docs for reference for this part. It's actually not repetitive, using this code will work for all modals in the future. I don't think this needs to be refactored further.

2024-06-19 09:51 UTC, hardikbhatia777 commented
> I left a small comment in one file. We are not running a linter here so, it is important that you use it locally. For example: normally, we use strings with single quotes.
> 
> Other points: let's prefer i18n keys than hardcoded strings. Also, always take a look on error handling (both items could be added later if we have time left).
> 
> Another point (maybe for later if we have time), it would be nice to have tests here if possible. Remember: this is open source and, in the future, we can have contributors.

You're right! Running a linter is very important. I've configured the same linter used in the core server docs to be used in the app. 

As for the i18n files, I looked at a lot of other apps and the docs. It seems hard coded strings are the only way to go in places where `i18nLabel` prop isn't explicitly defined (for example - placeholder texts). I'll keep looking into it for the mean time.

2024-06-21 02:32 UTC, scuciatto approved these changes

2024-06-21 02:33 UTC, scuciatto approved these changes

2024-06-24 12:10 UTC, merged