feat: Quick polls
RocketChat/AgileBot pull request #3
Opened 2024-07-21 10:20 UTC by hardikbhatia777

/quickpoll - Creates a quick poll

2024-07-29 13:17 UTC, scuciatto commented on commands/Poll.ts
> +		const time = args[0];
Wouldn't it be good to add error handling for parsing time? This would improve robustness.

2024-07-29 13:25 UTC, scuciatto requested changes

2024-07-29 13:25 UTC, scuciatto commented on commands/Poll.ts
> +		const blockBuilder = modify.getCreator().getBlockBuilder();
Blockbuilder is deprecated. We should use UIKit instead. We have discussed it here: https://open.rocket.chat/group/RLzgTEq2ngE2cMnMF?msg=tN8Sc895GFpHmkD4u

2024-07-29 13:25 UTC, scuciatto commented on commands/Poll.ts
> +		const time = args[0];
Can we add error handling for parsing time? This would improve robustness.

2024-07-29 15:58 UTC, hardikbhatia777 commented on commands/Poll.ts
> +		const time = args[0];
Added checks to ensure it's a valid (non-zero and below 10000) integer.

2024-07-29 15:59 UTC, hardikbhatia777 commented on commands/Poll.ts
> +		const blockBuilder = modify.getCreator().getBlockBuilder();
Done :)

2024-07-31 10:32 UTC, scuciatto approved these changes

2024-07-31 10:32 UTC, merged